---
- name: Apt install tools
  apt: name='{{ item }}' update_cache=yes
  with_items:
    - git
    - build-essential

- name: Ensure rolespec user exist
  user: name={{ rolespec_user }} state=present

- name: Ensure rolespec paths exist
  file: path={{ item }} state=directory owner={{ rolespec_user }} group={{ rolespec_user }} mode='0755'
  with_items:
      - '{{ rolespec_path }}'
      - '{{ rolespec_config_path }}'
      - '{{ rolespec_certs_path }}'
      - '{{ rolespec_templates_path }}'

- name: Download rolespec
  unarchive:
    src: '{{ rolespec_download_url }}'
    dest: '{{ rolespec_path }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    owner: '{{ rolespec_user }}'
    group: '{{ rolespec_user }}'
    creates: '{{ rolespec_path }}/bin'
