---
- name: Apt install tools
  apt: name='{{ item }}' update_cache=yes
  with_items:
    - git
    - build-essential

- name: Ensure rolespec user exists
  user: name='{{ rolespec_user }}'

- name: Create rolespec directory
  file: state=directory path='{{ rolespec_path }}' owner='{{ rolespec_user }}' group='{{ rolespec_user }}' mode='775'
  when: rolespec_path| default(False)
  register: rolespec_path_register
  failed_when: rolespec_path_register.failed|default(False) and rolespec_path_register.group != 'dialout'
