#!/bin/bash
# -*- bash -*-

# This gives you access to the custom DSL
. "${ROLESPEC_LIB}/main"

# Install a specific version of Ansible
install_ansible

# Install requirements.yml
ansible-galaxy install -r requirements.yml

# Check syntax first, and then that the playbook runs
assert_playbook_runs

# Check that the playbook is idempotent
assert_playbook_idempotent
